import InputDropdown from "./component/InputDropdown.js";
import InputWrapper from "./component/InputWrapper.js";
import Processing from "./dataProcessing/Processing.js";
import FormData from "./data/FormData.js";
import TextBox from "./component/TextBox.js";
import DesignForm from "./component/DesignForm.js";
import Page from "./component/Page.js";
import Story from "./component/Story.js";
import DesignPageForm from "./component/DesignPageForm.js"
import DesignStoryForm from "./component/DesignStoryForm.js"
import DesignScreen from "../screen/DesignScreen.js";
import ViewPage from "./component/viewPage.js";
import ViewStory from "./component/viewStory.js";
import ViewTextBox from "./component/viewTextBox.js";
import ReadStoryScreen from "../screen/ReadStoryScreen.js";